vendor: Aruba
name: Aruba KaaS
version: v1.0.0
website_url: https://my.arubacloud.com
documentation_url: https://kb.cloud.it/cmp/container/kubernetes.aspx
type: hosted
description: 'Aruba Cloud Managed Kubernetes solution'